### ISSUE TITLE
Specifics on how to link HTML to some godoc website's CSS and JS files.

### ISSUE THREAD

**Issue by urban-wombat** [fluhus/godoc-tricks#1]
I would like to use your trick: Link your HTML to some godoc website's CSS and JS files.

But I'm unclear about where to put references to:
* http://golang.org/
* script files

And could you provide the godoc command line you use to do this please?

**Comment by fluhus** [comment]
Actually at the time of writing that trick I was just getting to know the godoc tool. I looked into it now, and it seems that there is a better solution:

1. Add your packages to GOPATH.
2. Run `godoc -http ":8080"`
3. Browse to http://localhost:8080/pkg/ and you should see your godoc nicely rendered.

Let me know how this works for you, and I'll update the trick!

**Comment by urban-wombat** [comment]
Hi Amit

I think I followed the instructions correctly. What resulted at
http://localhost:8080/pkg/ was the same as the Go package godoc at
https://golang.org/pkg/

Apologies if I've got it wrong.

I wonder if you have a script you use for building your package godoc?

Your godoc looks very nice and I want to put mine onto Github nicely
formatted too.

Regards, Malcolm

**Comment by fluhus** [comment]
Your godoc is already online. :)
https://godoc.org/github.com/urban-wombat/gotable
I think they crawl Github automatically and update their Godoc site.

Regarding `godoc -http` - yes, that what you should get, and it should also include the packages in your GOPATH. So you should be able to scroll down and see your package alongside the standard packages. Just make sure your packages are indeed in GOPATH (available for `go install` for example).

Let me know if you still can't see it.

**Comment by urban-wombat** [comment]
Hi Amit

Yes, I can now see it at https://godoc.org/github.com/urban-wombat/gotable and
also see that it is searchable from https://godoc.org/

It looks great!

I made a few minor changes to test how it is updated. Here's what I think
is happening (correct me if I'm wrong):
- Github is updating the godoc at godoc.org/github.com automatically (as
you thought).
- There's no need to run godoc locally on my machine (which I had been
doing).

I tested this by simply changing some of the internal comments in my source
code and syncing it to github (and NOT running godoc locally). With a few
seconds the https://godoc.org/github.com/urban-wombat/gotable site was
updated and reflected the changes.

Perhaps the https://godoc.org/github.com/urban-wombat/gotable documentation
was appearing there all along?

Regards, Malcolm

**Comment by fluhus** [comment]
Hi Malcolm,
Yes, exactly! The Godoc site updates automatically as you push your changes to github.com. Your godoc probably was there all along.
The godoc command that you run works only on your local machine and reflects your local changes. It doesn't push anything online. But it's good for previewing your godoc before you push your commits.

**Comment by urban-wombat** [comment]
Thanks Amit.

I understand now. And the godoc looks great!

Regards, Malcolm

**Comment by fluhus** [comment]
Thank you for reporting! I have updated the tutorial with our new insights:
https://godoc.org/github.com/fluhus/godoc-tricks#HTML
https://godoc.org/github.com/fluhus/godoc-tricks#Github
