### ISSUE TITLE
Can't display on pkg.go.dev due to lack of license

### ISSUE THREAD

**Issue by jlucktay** [fluhus/godoc-tricks#3]
Hi there, and thank you for this repo! I refer to it quite a lot.

There was an issue with this package not showing up on the new pkg.go.dev site and giving a 404, so I e-mailed them to inquire about it which they were able to fix.

However, the package does not have a license, so it can't be shown there just yet.

Please have a look at [their license policy](https://pkg.go.dev/license-policy) and consider [choosing a license](https://choosealicense.com) for this package. Cheers!

**Comment by fluhus** [comment]
Hi @jlucktay, thank you for the input!

The legal aspects of open source are definitely not my strong side. :)
I've added an MIT license, based on my (uneducated) judgement. I hope it helps.

Right now the [docs site](https://pkg.go.dev/mod/github.com/fluhus/godoc-tricks?tab=versions) is not yet up to speed. Do you know what it takes for it to update?

**Comment by eduncan911** [comment]
You need to have a Release tag in the format of:

    v0.0.0

`v` must be prefixed, and three numbers for version.  For example:

    v1.0.0
    v0.0.1
    v6.2.7

Go modules are not required, as my packages have shown up without go modules.

**Comment by fluhus** [comment]
I added a [release](https://github.com/fluhus/godoc-tricks/releases/tag/v1.0.0). Not sure what the next step is. The [about page](https://go.dev/about#adding-a-package) says I need to "simply fetch it from proxy.golang.org".

How do you simply fetch stuff from proxy.golang.org?

**Comment by eduncan911** [comment]
The most reliable way I've found is to `curl` this url with the tag (I've added it to my github actions cicd pipelines, so it's always there immediately):

```
$ curl https://sum.golang.org/lookup/github.com/fluhus/godoc-tricks@v1.0.0
840009
github.com/fluhus/godoc-tricks v1.0.0 h1:1jIf/PnkaqMe+LLwOfYsVaCZ5dhcxUPHLAHur9geBCk=
github.com/fluhus/godoc-tricks v1.0.0/go.mod h1:1N650FoAiSfLt9dnD/ZxopiilNjtw+H8ocjRFbPWW2E=

go.sum database tree
840010
wxDxQvfKZV82mhTcQ+EDmORgADpcRenCcZwAUZ79a7s=

— sum.golang.org Az3grlNMZCXj7YIMnVQOh5DL5wUa3k7sO+3SNiuyEf3BjgjKdMoui/lJgrw6BRGCOVgoO7EBRGEhTGaQleq8ezuEqAY=
```

And now, it shows up!  Version 1.0.0

https://pkg.go.dev/github.com/fluhus/godoc-tricks

Enjoy!

**Comment by fluhus** [comment]
Awesome, thanks!

I'd love to learn about that proxy lookup you did. Where can I find documentation for that?

@jlucktay, can you please confirm that it looks as you expected? Feel free to close the issue if so.

**Comment by eduncan911** [comment]
Lots of hacking around.  In the help or more info, it mentions proxy stuff but I never got it to work.

However, some obscure text talks about getting hashes - which is what I did above.  And I found it's a reliable way of obtaining new tags immediately.
