### ISSUE TITLE
Add an example of how to do copyright headers

### ISSUE THREAD

**Issue by xiegeo** [fluhus/godoc-tricks#6]
While looking for a reference for how to do copyright headers in go files I found this helpful repo. Although I did not get my answer here, I found it at https://medium.com/@elliotchance/godoc-tips-tricks-cda6571549b. Please consider adding an example here too to help other gophers. Thank you.

**Comment by fluhus** [comment]
Hi, apologies for the delayed response! Got caught up in so much CODIV-related work that I neglected my repositories.

What exactly is missing for you? Separating the headers from the package godoc itself?

**Comment by eduncan911** [comment]
Maybe he means to edit `doc.go` and insert an example Copyright example at the top?

> Package level documentation must be in a continuous comment immediately preceding the packagestatement. If there is a blank line between the comment and the packagestatement it will be discarded. This is how you add comments that should or should not be included in the general package documentation.

So, maybe he means to add something at the top such as:

```
// Copyright Some Company Corp can go here. It is ignored 
// because of the space after "All Rights Reserved"
// All Rights Reserved

// Package godoctricks is a tutorial that deals with tricks for making your
// godoc organized and neat. This is a compilation of tricks I've collected and
// couldn't find a comprehensive guide for.
//
// Notice that this doc is written in godoc itself as package documentation.
// The defined types are just for making the table of contents at the
// head of the page; they have no meanings as types.
//
// If you have any suggestion or comment, please feel free to open an issue on
// this tutorial's GitHub page!
//
// By Amit Lavon
package godoctricks
```

**Comment by eduncan911** [comment]
Added a PR: https://github.com/fluhus/godoc-tricks/pull/7

**Comment by xiegeo** [comment]
Yes, something like what @eduncan911 did.

**Comment by fluhus** [comment]
Thank you @eduncan911 !
