### ISSUE TITLE
Expand examples for exhausting testing

### ISSUE THREAD

**Issue by oliverpool** [fluhus/godoc-tricks#9]
First of all, thank you for this great resource !

I have been using it to develop a system to self-host the documentation on vanity URLs: it allowed me to test most of the functionalities very conveniently: https://code.pfad.fr/vanitydoc (doc is still lacking, but the code is working :see_no_evil:)

I have a couple of suggestions to improve the coverage of the features:
- Add others `type` (currently exclusively `int`)
  * a `struct` with fields (commented, exported, unexported) - #12
  * an `interface` - #13
- a "whole file example" (see https://go.googlesource.com/blog/+/da446da101b2109b6e2620b626056f86e6dbc490/_content/examples.article) - #14
- More [examples levels](https://codeberg.org/pfad.fr/vanitydoc/src/branch/main/pkg/html.go#L115-L138) (`package` and `type` level already exist) #15 
  * for `Func` 
  * for `TypeFunc`
  * for `Methods`
 - format the code using gofmt (it adjusts some whitespace) - #10
 - add other kinds of notes (only `BUG` are present for now) #16
 - link to existing identifiers (with square brackets) #17

Before opening some PRs, I want to know if you think that such additions would be welcome.

**Comment by fluhus** [comment]
Hi @oliverpool,
Really sorry for the late response!
Happy to hear that this document is helpful for you.
Thank you very much for your contribution! You are welcome to send the other ones as well.
(Let's do them one by one to avoid a merge salad 😀)

Thanks!

**Comment by oliverpool** [comment]
I have created a first batch of 3 independent PRs (see above). I will let you review them before going further.

**Comment by fluhus** [comment]
The changes look great, thanks a lot!
Are there more things you would like to add?

**Comment by oliverpool** [comment]
Yes, I would like to add the following:

- More [examples levels](https://codeberg.org/pfad.fr/vanitydoc/src/commit/66eaf1e5136aed9972b75522ce44a8d617d7e38a/pkg/html.go#L160-L185) (`package` and `type` level already exist)
  * for `Func` 
  * for `TypeFunc`
  * for `Methods`
 - add other kinds of notes (only `BUG` are present for now)
 - link to existing identifiers (with square brackets)

**Comment by fluhus** [comment]
Sounds good. The last bullet, is it related to the [documentation links](https://pkg.go.dev/github.com/fluhus/godoc-tricks#hdr-Documentation_Links) part?

**Comment by oliverpool** [comment]
Yes, simply using actual package names, so that actual links are generated

```
//   - [Name] or [Name.Name] for a member of the current package
//   - [pkg], [pkg.Name] or [pks.Name.Name] for a member of a foreign package
```

**Comment by fluhus** [comment]
Cool, you can go ahead :)

**Comment by oliverpool** [comment]
With the recently opened 3 PRs, this issue can be considered done!

(discussion can continue there)

**Comment by fluhus** [comment]
Thanks for all the additions! All merged.

(and sorry for the late response)

**Comment by oliverpool** [comment]
Thank you for merging them all! (I wasn't fast either :)

Could you add a new tag, so that it gets picked up by https://pkg.go.dev/github.com/fluhus/godoc-tricks ? (1.4.2 or 1.5.0)

**Comment by fluhus** [comment]
Right, added!

**Comment by oliverpool** [comment]
If you want to have a look, here is how `godoc-tricks` is rendered with `vanitydoc`: https://code.pfad.fr/fluhus/godoc-tricks
